
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Sep 13 2024 11:41:28 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ImageButton extends ContentItem {
    public image!: Elements.AssetsElement;
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public target!: Elements.TextElement;
}
