
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Oct 10 2022 16:01:57 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Pressrelaseitem extends ContentItem {
    public image!: Elements.AssetsElement;
    public websiteLink!: Elements.TextElement;
    public name!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'website_link') {
                    return 'websiteLink';
                }
                return elementName;
            })
        });
    }
}
