
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Jul 16 2024 16:23:38 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Serviceitem extends ContentItem {
    public name!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public link!: Elements.TextElement;
}
