
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Oct 04 2024 11:36:47 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Sessionspeaker extends ContentItem {
    public name!: Elements.TextElement;
    public portfolio!: Elements.LinkedItemsElement<ContentItem>;
    public sessionbreak!: Elements.NumberElement;
    public partnershipwith!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public location!: Elements.TextElement;
    public time!: Elements.TextElement;
    public startTime!: Elements.DateTimeElement;
    public endTime!: Elements.DateTimeElement;
    public room!: Elements.TextElement;
    public date!: Elements.LinkedItemsElement<ContentItem>;
    public tags!: Elements.TextElement;
    public track!: Elements.LinkedItemsElement<ContentItem>;
    public sessionType!: Elements.LinkedItemsElement<ContentItem>;
    public sessionTopic!: Elements.LinkedItemsElement<ContentItem>;
    public speakers!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'start_time') {
                    return 'startTime';
                }
                if (elementName === 'end_time') {
                    return 'endTime';
                }
                if (elementName === 'session_type') {
                    return 'sessionType';
                }
                if (elementName === 'session_topic') {
                    return 'sessionTopic';
                }
                return elementName;
            })
        });
    }
}
