
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 10 2024 09:54:01 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Speakers2024 extends ContentItem {
    public heading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
