
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Sep 11 2024 09:25:46 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Startuppitchpage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public videolink!: Elements.TextElement;
    public aboutheading!: Elements.TextElement;
    public aboutdescription!: Elements.TextElement;
    public aboutimage!: Elements.AssetsElement;
    public unicornsectionctaheading!: Elements.TextElement;
    public unicornsectionctasubheading!: Elements.TextElement;
    public unicornsectionctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public genericsectionctaheading!: Elements.TextElement;
    public genericsectionctasubheading!: Elements.TextElement;
    public genericsectionctabackgroundimage!: Elements.AssetsElement;
    public genericsectionctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public tailendheading!: Elements.TextElement;
    public tailendsubheading!: Elements.TextElement;
    public tailendbackgroundimage!: Elements.AssetsElement;
}
