
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 03 2024 09:13:27 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Statsitem extends ContentItem {
    public name!: Elements.TextElement;
    public count!: Elements.TextElement;
    public image!: Elements.AssetsElement;
}
